[tool.poetry]
name = "nb-cli"
version = "0.1.0"
description = "CLI for nonebot2"
authors = ["yanyongyu <yanyongyu_1@126.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pyinquirer = "^1.0.3"
click = "^7.1.2"
pyfiglet = "^0.8.post1"
six = "^1.15.0"
colorama = "^0.4.3"

[tool.poetry.dev-dependencies]
yapf = "^0.30.0"

[tool.poetry.scripts]
nb = "nb_cli.__main__:main"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
